language: bash
os:
  - linux
sudo: true
dist: trusty
# travis requires that you update manually, and provides this key to trigger it
apt:
  update: true
before_install:
  # as per a number of comments online, this might mitigate some flaky fails...
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6; fi
  # apt update tends to be flaky in travis, retry up to 3 times on failure
  # https://docs.travis-ci.com/user/common-build-problems/#travis_retry
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_retry travis_retry sudo apt update; fi
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch --unshallow || true
install: 'make deps'
script: 'make test'
